#Import Modules
from iNaturalist_Modules.get_park_ids import *
from iNaturalist_Modules.get_places import *
from iNaturalist_Modules.get_observations import *
from iNaturalist_Modules.taxon import *
from Modules.push_to_stage import *
from Modules.set_up_logs import *
from Modules.remove_local_data import *

# Set Up Variables
park_list = [
            # "Acadia National Park",
            # "American Samoa National Park",
            # "Arches National Park",
            # "Badlands National Park",
            # "Big Bend National Park",
            # "Biscayne National Park",
            # "Black Canyon of the Gunnison National Park",
            # "Bryce Canyon National Park",
            # "Canyonlands National Park",
            # "Capitol Reef National Park",
            # "Carlsbad Caverns National Park",
            # "Channel Islands National Park",
            # "Congaree National Park",
            # "Crater Lake National Park",
            # "Cuyahoga Valley National Park",
            # "Death Valley National Park",
            # "Denali National Park",
            # "Dry Tortugas National Park",
            # "Everglades National Park",
            # "Gates of the Arctic National Park & Preserve",
            # "Gateway Arch National Park",
            # "Glacier Bay National Park & Preserve",
            # "Glacier National Park",
            # "Grand Canyon National Park",
            # "Grand Teton National Park",
            # "Great Basin National Park",
            # "Great Sand Dunes National Park & Preserve",
            # "Great Smoky Mountains National Park",
            # "Guadalupe Mountains National Park",
            # "Haleakalā National Park",
            # "Hawaiʻi Volcanoes National Park",
            # "Hot Springs National Park",
            # "Indiana Dunes National Park",
            # "Isle Royale National Park",
            # "Joshua Tree National Park",
            # "Katmai National Park & Preserve",
            # "Kenai Fjords National Park",
            # "Kings Canyon National Park",
            # "Kobuk Valley National Park",
            # "Lake Clark National Park & Preserve",
            # "Lassen Volcanic National Park",
            # "Mammoth Cave National Park",
            # "Mesa Verde National Park",
            # "Mount Rainier National Park",
            # "New River Gorge National Park & Preserve",
            # "North Cascades National Park",
            # "Olympic National Park",
            # "Petrified Forest National Park",
            # "Pinnacles National Park",
            # "Redwood National Park",
            # "Rocky Mountain National Park",
            # "Saguaro National Park",
            # "Sequoia National Park",
            # "Shenandoah National Park",
            # "Theodore Roosevelt National Park",
            # "Virgin Islands National Park",
            # "Voyageurs National Park",
            # "White Sands National Park",
            # "Wind Cave National Park",
            # "Wrangell–St. Elias National Park & Preserve",
            # "Yellowstone National Park",
            # "Yosemite National Park",
            # "Zion National Park",
            # "Kruger National Park",
            # "Monument Valley",
            # "Niagara Falls", 
            # "Muir Woods",
            # "Point Reyes", 
            # "Peak District National Park", 
            "Table Mountain National Park",
            # "Lake District National Park",
            # "Snowdonia National Park",
            # "Blue Mountains National Park, NSW, AU (NPWS Tenure polygon",
            # "Banff National Park",
            # "Parque Nacional Galapagos",
            # "Royal National Park, NS, AU",
            # "Jasper National Park, AB, CA",
            # "Kosciuszko National Park",
            # "Pacific Rim National Park Reserve",
            # "Addo Elephant National Park MPA, ZA",
            # "Kakadu National Park",
            # "Serengeti National Park",
            # "Parque Nacional Iguazú, MN, AR",
            # "Parque Nacional Torres del Paine, MA, CL",
            # "Cumbres de Monterrey",
            # "Nationalpark Hohe Tauern",
            # "Triglavski narodni park",
            # "Plitvička Jezera, LS, HR",
            # "Khao Yai",
            # "Sagarmatha",
            # "Namib-Naukluft",
            # "Parque Nacional Manuel Antonio",
            # "Gunung Mulu",
            # "Komodo National Park World Heritage Site, ID",
            # "Parco Nazionale delle Cinque Terre",
            # "Area marina protetta Cinque Terre, Liguria, IT",
            # "Westland Tai Poutini",
            # "Bwindi Impenetrable",
            # "Parque Nacional Rincón de la Vieja, GU, CR",
            # "Great Barrier Reef, AU",
            # "Masai Mara",
            # "Durmitor National Park World Heritage Site, ME",
            # "Parc National des Calanques, FR",
            # "Parque Nacional Yasuní, ECU",
            # "Parque Nacional Corcovado",
            # "Gunung Leuser",
            # "Parc National de la Salonga",
            # "Wadi Rum",
            # "tassili n'ajjer",
            # "Parque Nacional Monte León, SC, AR",
            # "Wood Buffalo National Park, AB, CA",
            # "Urho Kekkosen kansallispuisto",
            # "Huascarán",
            # "Altai Tavan Bogd",
            # "Etosha National Park",
            # "Parque Nacional de Doñana, ES",
            # "Parco Nazionale del Cilento, Vallo di Diano e Alburni, Campania, IT",
            # "samaria",
            # "Svalbard and Jan Mayen",
            # "Auyuittuq National Park, CA, NU",
            # "Ranomafana National Park, FI, MG",
            # "Jiuzhaigou Valley Scenic and Historic Interest Area, SC, CN",
            # "Tai National Park, CI",
            # "Mole National Park",
            # "Tubbataha Reefs",
            # "Northeast Greenland National Park, GL",
            # "Jeju KR",
            # "Bukhansan National Park, KR",
            # "Khangchendzonga ",
            # "Fujikawaguchiko, JP, YN",
            # "Danum Valley Conservation Area, SA, MY",
            # "Fernando de Noronha",
            # "Parque Nacional da Chapada dos Veadeiros", 
            # "Lençóis Maranhenses",
            # "Canaima National Park",
            # "Parque Nacional da Serra dos Órgãos",
            # "El Yunque National Forest",
            # "Parque Nacional del Teide",
            # "Thingvellir",
            # "Jotunheimen", 
            # "Białowieża Forest World Heritage Site",
            # "chobe-national-park",
            # "Simien Mountains",
            # "Ras Mohammed National Park",
            # "Mount Huangshan World Heritage Site ",
            # "Ha long bay",
            # "Kaziranga",
            # "Sundarbans National Park",
            # "Nanhu Taroko",
            # "Gunung Mulu National Park",
            # "Uluru-Kata Tjuta",
            # "Tongariro National Park World Heritage Site",
            # "Papahānaumokuākea World Heritage Site",
            # "Ningaloo Coast World Heritage Site",
            # "Franklin-Gordon Wild Rivers",
            # "Morne Trois Pitons",
            # "Christoffel National Park",
            # "Hol Chan Marine Reserve",
            # "Belize Barrier Reef Reserve System",
            # "Blue and John Crow Mountains World Heritage Site",
            # "Alejandro de Humboldt",
            # "Varirata National Park",
            # "Lenskie stolby",
            # "Плато Путорана Putorana Plateau World Heritage Site",
            # "Sian Ka'an Biosphere Reserve",
            # "Parque Nacional Cabo Pulmo, BS, MX",
            "Parque Nacional Cañón del Sumidero",
            "Parque Nacional Iztaccihuatl - Popocatepetl"

        ]
days_back = 1
directory = "Data/"
stage = 'nature_stg'
schema = 'JC_NATURE'
user = 'SVC_SNOWFLAKE_PYTHON_JC'
warehouse = 'dataschool_wh'
database = 'TIL_DATA_ENGINEERING'
account = os.environ["ACCOUNT"]
password = os.environ["PASSWORD"]
private_key = "snowflake_key.p8"
#Run Pipeline
place_ids = fetch_park_id(park_list)
get_places(place_ids)
get_observations(place_ids, days_back)
get_taxon(stage, schema, database, account, password, private_key, warehouse, user)
push_to_stage(directory, stage, schema, database, account, password, private_key, warehouse, user) 
remove_local_data(directory, stage, schema, database, account, password, private_key, warehouse, user)

